#########################
## Global Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
# File Options
files:
  include: scss/**/*.s+(a|c)ss
# Rule Configuration
rules:
  attribute-quotes:
    - 1
    - include: true
  bem-depth:
    - 1
    - max-depth: 1
  border-zero:
    - 1
    - convention: none
  brace-style:
    - 2
    - style: stroustrup
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedbem
  clean-import-paths:
    - 2
    - leading-underscore: false
    - filename-extension: false
  declarations-before-nesting: 2
  empty-args:
    - 1
    - include: false
  empty-line-between-blocks:
    - 1
    - include: true
    - allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 1
    - include: false
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 1
    - allow-leading-underscore: false
    - convention: camelcase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  id-name-format:
    - 1
    - convention: hyphenatedbem
  indentation:
    - 2
    - size: 4
  max-file-line-count:
    - 1
    - length: 300
  max-line-length:
    - 1
    - length: 80
  mixin-name-format:
    - 1
    - allow-leading-underscore: false
    - convention: camelcase
    - convention-explanation: 'Mixin names must be written in camelCase'
  nesting-depth:
    - 1
    - max-depth: 2
  no-attribute-selectors: 2
  no-color-keywords: 2
  no-color-literals:
    - 2
    - allow-rgba: true
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
    - allow-element-with-class: false
    - allow-element-with-id: false
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-universal-selectors: 2
  no-url-domains: 0
  no-url-protocols: 0
  one-declaration-per-line: 2
  placeholder-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: hyphenatedbem
  property-sort-order:
    - 2
    - ignore-custom-properties: false
      order: alphabetical
  property-units:
    - 2
    - global: ['em', 'px', 'rem']
  pseudo-element: 2
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-around-operator:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  quotes:
    - 2
    - style: double
  trailing-semicolon:
    - 2
    - include: true
  url-quotes: 2
  variable-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: hyphenatedlowercase
    - convention-explanation: 'Variable names should be all lowercase with hyphens between each word'
  zero-unit:
    - 1
    - include: false